function DragForceVec = ComputeDragForceVec(ACVelVec,MachNumData,DragCoeffData,DragArea,WindVelVec,SoundSpeed,AirDensity)
RelWindVelVec = WindVelVec - ACVelVec;
MachNum = norm(RelWindVelVec)/SoundSpeed;
DragCoeff = interp1(...
 MachNumData,DragCoeffData,MachNum,'spline');
DragForceVec =...
 0.5*DragCoeff*AirDensity*DragArea...
 *norm(RelWindVelVec)*RelWindVelVec;