function ThrustForce = ComputeThrustMag(Time,BurnTime,NozzleEff,C_Star,ExitPressure,ChamberPressure,ExpAreaRatio,PropFlowRate,SpHeatRatio,GravAccelSL,AtmPressure)
if Time <= BurnTime
 SpImpulse =...
  NozzleEff*(C_Star*SpHeatRatio/GravAccelSL...
  *sqrt((2/(SpHeatRatio - 1))*((2/(SpHeatRatio + 1))...
  ^((SpHeatRatio + 1)/(SpHeatRatio - 1)))...
  *(1 - ((ExitPressure/ChamberPressure)...
  ^((SpHeatRatio - 1)/SpHeatRatio)))) + C_Star...
  *ExpAreaRatio/(GravAccelSL*ChamberPressure)...
  *(ExitPressure - AtmPressure));
 ThrustForce =...
  SpImpulse*PropFlowRate*GravAccelSL;
else
 ThrustForce = 0;
end