function wind_vec = wind(...
    time_since_launch,... 
    height,...
    env)

    spaceport_america_latitude = 32.9904;
    spaceport_america_longitude = 106.9750; % Coordinates from Google

    launch_time = 64800; % Just picked noon MST for now.
    launch_day = 349; % Just picked December 16 for now.
    
    wind_nominal = atmoshwm(...
        spaceport_america_latitude,...
        spaceport_america_longitude,...
        height,...
        'day', launch_day,...
        'seconds',launch_time + time_since_launch,...
        'model','quiet',... % No magnetic field stuff for now.
        'version', '14');
    
    wind_vec = [
        sampling.apply_uncertainty(...
            wind_nominal(2),...
            env.wind_zonal_uncertainty); %(WEST TO EAST AKA +X)
        sampling.apply_uncertainty(...
            wind_nominal(1),...
            env.wind_meridional_uncertainty); %(SOURTH TO NORTH AKA +Y)
        0];
end