function Cd_body = C_d_body(mach_num, vehicle, env)
    Cd_body = 0.053*(vehicle.AR_B)...
        *(mach_num/(aerodynamics.dynamic_pressure(mach_num, env)...
        *vehicle.fuselage_length))^(0.2);
end
