function animate(time, state, vehicle)
    % Animation settings
    scaling_factor = 3000;
    num_time_steps = length(time);
    color = [0.41 0.41 0.41];
    
    f = figure;
    f.Name = 'Flight Trajectory';
    f.NumberTitle = 'off';
    f.WindowState = 'maximized';
    
    vehicle.fin_root_chord = 0.8128;
    vehicle.fin_tip_chord = 0.34349944;
    
    %% Values for basic animation
    fuselage_vec_init = scaling_factor*[vehicle.fuselage_length; 0; 0];
    fin(1).vec_init = scaling_factor*[0; -vehicle.fuselage_length/3; 0];
    fin(2).vec_init = scaling_factor*[0; 0; vehicle.fuselage_length/3];
    fin(3).vec_init = scaling_factor*[0; vehicle.fuselage_length/3; 0];
    fin(4).vec_init = scaling_factor*[0; 0; -vehicle.fuselage_length/3];
    
    %% Values for "better" animation
    [nose_init, body_init, fin1_init, fin2_init, fin3_init, fin4_init] = ...
        animation.gen_rocket(vehicle);
    
    % Apogee
    [apogee, apogee_time] = util.find_apogee(time, state(:,3));
        
    for time_step_num = 1:num_time_steps
        curr_orientation = state(time_step_num, 4:7);
        
        %% Plot basic animation
        subplot(1,2,1);
        fuselage_vec = coordinate.to_inertial_frame(curr_orientation, fuselage_vec_init);
        % Plot line representing fuselage
        plot3(...
            [state(time_step_num,1), state(time_step_num,1) + fuselage_vec(1)]',...
            [state(time_step_num,2), state(time_step_num,2) + fuselage_vec(2)]',...
            [state(time_step_num,3), state(time_step_num,3) + fuselage_vec(3)]',...
            'k',...
            'LineWidth',...
            1.5);
        hold on;
        % Plot lines representing fins
        for fin_num = 4:-1:1
            fin(fin_num).vec = coordinate.to_inertial_frame(curr_orientation, fin(fin_num).vec_init);
            plot3(...
                [state(time_step_num,1), state(time_step_num,1) + fin(fin_num).vec(1)]',...
                [state(time_step_num,2), state(time_step_num,2) + fin(fin_num).vec(2)]',...
                [state(time_step_num,3), state(time_step_num,3) + fin(fin_num).vec(3)]',...
                'k',...
                'LineWidth',...
                1.5);
        end
        axis([-75000 75000 -75000 75000 0 150000]);
        daspect([1 1 1]);
        
        hold off;
        grid on;
        %% Plot "better" animation
        subplot(1,2,2);
        
        
        %zlim([0 vehicle.fuselage_length] + state(time_step_num,3));
%         
%         [x_b,y_b,z_b] = animation.rotate_part(body_init, curr_orientation);
%         [x_n, y_n, z_n] = animation.rotate_part(nose_init, curr_orientation);
%         [x_f1, y_f1, z_f1] = animation.rotate_fin(fin1_init, curr_orientation);
%         [x_f2, y_f2, z_f2] = animation.rotate_fin(fin2_init, curr_orientation);
%         [x_f3, y_f3, z_f3] = animation.rotate_fin(fin3_init, curr_orientation);
%         [x_f4, y_f4, z_f4] = animation.rotate_fin(fin4_init, curr_orientation);
%         
%         surf(...
%             x_b + state(time_step_num,1),...
%             y_b + state(time_step_num,2),...
%             z_b + state(time_step_num,3),...
%             'facecolor',color ,'LineStyle', 'none', 'EdgeColor', 'w');
        surf(...
            body_init(:,:,1) + state(time_step_num,1),...
            body_init(:,:,2) + state(time_step_num,2),...
            body_init(:,:,3) + state(time_step_num,3),...
            'facecolor',color ,'LineStyle', 'none', 'EdgeColor', 'w');
        hold on;
        
        surf(...
            nose_init(:,:,1) + state(time_step_num,1),...
            nose_init(:,:,2) + state(time_step_num,2),...
            nose_init(:,:,3) + state(time_step_num,3),...
            'facecolor',color ,'LineStyle', 'none', 'EdgeColor', 'w');
        fill3(...
            fin1_init(1,:) + state(time_step_num,1),... 
            fin1_init(2,:) + state(time_step_num,2),...
            fin1_init(3,:) + state(time_step_num,3),...
            color);
        fill3(...
            fin2_init(1,:) + state(time_step_num,1),... 
            fin2_init(2,:) + state(time_step_num,2),...
            fin2_init(3,:) + state(time_step_num,3),...
            color);
        fill3(...
            fin3_init(1,:) + state(time_step_num,1),... 
            fin3_init(2,:) + state(time_step_num,2),...
            fin3_init(3,:) + state(time_step_num,3),...
            color);
        fill3(...
            fin4_init(1,:) + state(time_step_num,1),... 
            fin4_init(2,:) + state(time_step_num,2),...
            fin4_init(3,:) + state(time_step_num,3),...
            color);
%         surf(...
%             x_n + state(time_step_num,1),... 
%             y_n + state(time_step_num,2),...
%             z_n + state(time_step_num,1),...
%             'facecolor',color);
% 
%         fill3(...
%             x_f1 + state(time_step_num,1),...
%             y_f1 + state(time_step_num,2),...
%             z_f1 + state(time_step_num,3),...
%             color);
%         fill3(...
%             x_f2 + state(time_step_num,1),...
%             y_f2 + state(time_step_num,2),...
%             z_f2 + state(time_step_num,1),...
%             color);
%         fill3(...
%             x_f3 + state(time_step_num,1),...
%             y_f3 + state(time_step_num,2),...
%             z_f3 + state(time_step_num,3),...
%             color);
%         fill3(...
%             x_f4 + state(time_step_num,1),...
%             y_f4 + state(time_step_num,2),...
%             z_f4 + state(time_step_num,3),...
%             color);
        xlim([-2 2] + state(time_step_num,1));
        ylim([-2 2] + state(time_step_num,2));
        grid on;
        hold off;
        
        %% Legend
        subplot(1,2,1);
        sim_time = time(time_step_num);
        altitude = state(time_step_num,3);
        apogee_msg = '';
        if sim_time >= apogee_time
            apogee_msg = ['Apogee: ', num2str(apogee), ' m'];
        end
        msg = ['Time: ', num2str(sim_time), ' s  Altitude: ', num2str(altitude), ' m  ',  apogee_msg];

        text(-150000, 75000, 250000, msg);
        %   pause;
        %drawnow
        pause(0.0001)
        % End if touched ground
        if (state(time_step_num,3) < vehicle.launch_alt) && (state(time_step_num,10) < 0)
            break
        end
    end
end
