function [nose, body, fin1, fin2, fin3, fin4] = gen_rocket(vehicle)
    rot_quat = lin_alg.euler_to_quat([0 90 0]);
    body_length = vehicle.fuselage_length - vehicle.nose_length;
    body = animation.gen_body(...
        vehicle.fuselage_diameter/2,...
        body_length,...
        0,...
        0,...
        0);
    body = animation.rotate_part(body, rot_quat);
    
    nose = animation.gen_haack_series(...
        vehicle.fuselage_diameter/2,...
        vehicle.nose_length,...
        0,...
        0,...
        0,...
        vehicle.body_length);
    
    nose = animation.rotate_part(nose, rot_quat);
    
    fin1 = animation.gen_fin(vehicle, vehicle.fuselage_diameter/2, 0);
    fin2 = animation.gen_fin(vehicle, vehicle.fuselage_diameter/2, 90);
    fin3 = animation.gen_fin(vehicle, vehicle.fuselage_diameter/2, 180);
    fin4 = animation.gen_fin(vehicle, vehicle.fuselage_diameter/2, 270);
    
    fin1 = animation.rotate_fin(fin1, rot_quat);
    fin2 = animation.rotate_fin(fin2, rot_quat);
    fin3 = animation.rotate_fin(fin3, rot_quat);
    fin4 = animation.rotate_fin(fin4, rot_quat);
end