function Rocket = ComputeThrustMag(Global,Rocket,Time)
if Time <= Rocket.BurnTime
 Rocket.SpImpulse =...
  Rocket.NozzleEff*(Rocket.C_Star*Global.SpHeatRatio/Global.GravAccelSL...
  *sqrt((2/(Global.SpHeatRatio - 1))*((2/(Global.SpHeatRatio + 1))...
  ^((Global.SpHeatRatio + 1)/(Global.SpHeatRatio - 1)))...
  *(1 - ((Rocket.ExitPressure/Rocket.ChamberPressure)...
  ^((Global.SpHeatRatio - 1)/Global.SpHeatRatio)))) + Rocket.C_Star...
  *Rocket.ExpAreaRatio/(Global.GravAccelSL*Rocket.ChamberPressure)...
  *(Rocket.ExitPressure - Global.AtmPressure));
 Rocket.ThrustForce =...
  Rocket.SpImpulse*Rocket.PropFlowRate*Global.GravAccelSL;
else
 Rocket.ThrustForce = 0;
end