function force_ballute = f_ballute(...
    altitude,...
    v_ground,...
    v_apparent,...
    vehicle,... 
    env,...
    uncertainties)
%F_BALLUTE Computes force from ballutes.
%   Relatively simply model.
%   Advanced model here:
%   https://www.researchgate.net/publication/238563816_Six-Degree-of-Freedom_Model_of_a_Controlled_Circular_Parachute
    opening_alt = sampling.apply_uncertainty(...
        vehicle.ballute_alt,...
        'ballute_alt',...
        uncertainties);
    if (v_ground(3) < 0) && (altitude <= opening_alt)
        ballute_cd = sampling.apply_uncertainty(...
            vehicle.ballute_drag_coeff,...
            'CD_ballute',...
            uncertainties);
        total_area = vehicle.num_of_ballutes*pi*(vehicle.ballute_dia/2)^2;
        force_ballute = ...
            -0.5*ballute_cd*env.density*total_area...
            *norm(v_apparent)*v_apparent;
    else
        force_ballute = [0;0;0];
    end
end
