function force_chute = f_chute(...
    altitude,...
    v_ground,...
    v_apparent,...
    vehicle,...
    env,...
    uncertainties)
%F_CHUTE Computes force from chutes.
%   Relatively simply model.
%   Advanced model here:
%   https://www.researchgate.net/publication/238563816_Six-Degree-of-Freedom_Model_of_a_Controlled_Circular_Parachute
    opening_alt = sampling.apply_uncertainty(...
        vehicle.main_chute_alt,...
        'chute_alt',...
        uncertainties);
    if (v_ground(3) < 0) && (altitude <= opening_alt)
        chute_cd = sampling.apply_uncertainty(...
            vehicle.main_chute_drag_coeff,...
            'CD_chute',...
            uncertainties);
        total_area = vehicle.num_of_chutes*pi*(vehicle.main_chute_dia/2)^2;
        force_chute = ...
            -0.5*chute_cd*env.density*total_area...
            *norm(v_apparent)*v_apparent;
    else
        force_chute = [0;0;0];
    end
end
